# Generated by Django 5.0.4 on 2024-04-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_experience_position_alter_experience_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechStack',
        ),
    ]
