# Generated by Django 5.0.4 on 2024-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_delete_techstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/project_image'),
        ),
    ]
