# Generated by Django 5.0.4 on 2024-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
